// clicker-app/javascript/vue/final/src/App.vue
<template>
  <Counter :starting="0" :min="-100" :max="100"/>
</template>

<script lang="ts">
import Counter from './components/Counter.vue'

export default {
  name: 'App',
  components: {
    Counter
  },
}
</script>

<style>

html, body {
  margin: 0;
  padding: 0;
}

#app {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  width: 100vw;
  height: 100vh;
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  margin: 0;
  padding: 0;
  background: #363636;
  color: #d9d9d9;
  font-size: 10px;
}
</style>

// clicker-app/javascript/svelte/final/src/App.svelte
<script>
  // import Counter from "./components/Counter.svelte";
  import { counter } from "./lib/counter";

  let [number, { increment, decrement, reset }] = counter({});
</script>

<main>
  <!-- <Counter starting={100} min={102} max={100} /> -->
  <h1>{$number}</h1>
  <div class="container">
    <button on:click={decrement}>-</button>
    <button on:click={reset}>reset</button>
    <button on:click={increment}>+</button>
  </div>
</main>

<style>
  main {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    width: 100vw;
    height: 100vh;
    overflow: hidden;
    background: #363636;
    font-size: 10px;
    color: #e8e8e8;
  }

  h1 {
    font-size: 5rem;
  }

  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 1rem;
    font-size: 2rem;
  }

  button {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 0.5rem;
    margin: 0 0.25rem;
    min-width: 3.5rem;
    background: #999999;
    color: #e8e8e8;
    border: none;
  }
</style>
